// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/proto/types/delegate.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Delegate struct {
	DelegateID           uint64   `protobuf:"varint,1,opt,name=delegateID,proto3" json:"delegateID,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delegate) Reset()         { *m = Delegate{} }
func (m *Delegate) String() string { return proto.CompactTextString(m) }
func (*Delegate) ProtoMessage()    {}
func (*Delegate) Descriptor() ([]byte, []int) {
	return fileDescriptor_48cbd699f4c7e6fc, []int{0}
}

func (m *Delegate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delegate.Unmarshal(m, b)
}
func (m *Delegate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delegate.Marshal(b, m, deterministic)
}
func (m *Delegate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delegate.Merge(m, src)
}
func (m *Delegate) XXX_Size() int {
	return xxx_messageInfo_Delegate.Size(m)
}
func (m *Delegate) XXX_DiscardUnknown() {
	xxx_messageInfo_Delegate.DiscardUnknown(m)
}

var xxx_messageInfo_Delegate proto.InternalMessageInfo

func (m *Delegate) GetDelegateID() uint64 {
	if m != nil {
		return m.DelegateID
	}
	return 0
}

func (m *Delegate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Delegate)(nil), "types.Delegate")
}

func init() { proto.RegisterFile("proto/proto/types/delegate.proto", fileDescriptor_48cbd699f4c7e6fc) }

var fileDescriptor_48cbd699f4c7e6fc = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x87, 0x90, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0xfa, 0x29, 0xa9, 0x39, 0xa9, 0xe9, 0x89,
	0x25, 0xa9, 0x7a, 0x60, 0x41, 0x21, 0x56, 0xb0, 0xa8, 0x92, 0x0b, 0x17, 0x87, 0x0b, 0x54, 0x42,
	0x48, 0x8e, 0x8b, 0x0b, 0xa6, 0xc8, 0xd3, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x25, 0x08, 0x49,
	0x44, 0x48, 0x82, 0x8b, 0x3d, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x58, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xc6, 0x75, 0x32, 0x8f, 0x32, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b,
	0xce, 0xcf, 0xd5, 0xcf, 0xcc, 0x2f, 0x49, 0xad, 0x28, 0x28, 0xca, 0xcf, 0x4a, 0x4d, 0x2e, 0xd1,
	0xcf, 0xc8, 0x4c, 0xcf, 0xd0, 0x2d, 0x49, 0x4c, 0xca, 0x49, 0x85, 0xba, 0x26, 0x3d, 0x3f, 0x27,
	0x31, 0x2f, 0x1d, 0xe2, 0xa8, 0x24, 0x36, 0xb0, 0x98, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x8c,
	0x92, 0xf0, 0x92, 0xb0, 0x00, 0x00, 0x00,
}
