// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/proto/api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	types "github.com/iotexproject/high-table/proto/golang/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDelegateRequest struct {
	DelegateID           uint64   `protobuf:"varint,1,opt,name=delegateID,proto3" json:"delegateID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDelegateRequest) Reset()         { *m = GetDelegateRequest{} }
func (m *GetDelegateRequest) String() string { return proto.CompactTextString(m) }
func (*GetDelegateRequest) ProtoMessage()    {}
func (*GetDelegateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15eae2866f8410ca, []int{0}
}

func (m *GetDelegateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDelegateRequest.Unmarshal(m, b)
}
func (m *GetDelegateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDelegateRequest.Marshal(b, m, deterministic)
}
func (m *GetDelegateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDelegateRequest.Merge(m, src)
}
func (m *GetDelegateRequest) XXX_Size() int {
	return xxx_messageInfo_GetDelegateRequest.Size(m)
}
func (m *GetDelegateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDelegateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDelegateRequest proto.InternalMessageInfo

func (m *GetDelegateRequest) GetDelegateID() uint64 {
	if m != nil {
		return m.DelegateID
	}
	return 0
}

type GetDelegateResponse struct {
	Delegate             *types.Delegate `protobuf:"bytes,1,opt,name=delegate,proto3" json:"delegate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetDelegateResponse) Reset()         { *m = GetDelegateResponse{} }
func (m *GetDelegateResponse) String() string { return proto.CompactTextString(m) }
func (*GetDelegateResponse) ProtoMessage()    {}
func (*GetDelegateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15eae2866f8410ca, []int{1}
}

func (m *GetDelegateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDelegateResponse.Unmarshal(m, b)
}
func (m *GetDelegateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDelegateResponse.Marshal(b, m, deterministic)
}
func (m *GetDelegateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDelegateResponse.Merge(m, src)
}
func (m *GetDelegateResponse) XXX_Size() int {
	return xxx_messageInfo_GetDelegateResponse.Size(m)
}
func (m *GetDelegateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDelegateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDelegateResponse proto.InternalMessageInfo

func (m *GetDelegateResponse) GetDelegate() *types.Delegate {
	if m != nil {
		return m.Delegate
	}
	return nil
}

type UpdateDelegateRequest struct {
	Delegate             *types.Delegate `protobuf:"bytes,1,opt,name=delegate,proto3" json:"delegate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateDelegateRequest) Reset()         { *m = UpdateDelegateRequest{} }
func (m *UpdateDelegateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDelegateRequest) ProtoMessage()    {}
func (*UpdateDelegateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15eae2866f8410ca, []int{2}
}

func (m *UpdateDelegateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDelegateRequest.Unmarshal(m, b)
}
func (m *UpdateDelegateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDelegateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDelegateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDelegateRequest.Merge(m, src)
}
func (m *UpdateDelegateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDelegateRequest.Size(m)
}
func (m *UpdateDelegateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDelegateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDelegateRequest proto.InternalMessageInfo

func (m *UpdateDelegateRequest) GetDelegate() *types.Delegate {
	if m != nil {
		return m.Delegate
	}
	return nil
}

type UpdateDelegateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDelegateResponse) Reset()         { *m = UpdateDelegateResponse{} }
func (m *UpdateDelegateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDelegateResponse) ProtoMessage()    {}
func (*UpdateDelegateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15eae2866f8410ca, []int{3}
}

func (m *UpdateDelegateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDelegateResponse.Unmarshal(m, b)
}
func (m *UpdateDelegateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDelegateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateDelegateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDelegateResponse.Merge(m, src)
}
func (m *UpdateDelegateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDelegateResponse.Size(m)
}
func (m *UpdateDelegateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDelegateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDelegateResponse proto.InternalMessageInfo

func (m *UpdateDelegateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*GetDelegateRequest)(nil), "api.GetDelegateRequest")
	proto.RegisterType((*GetDelegateResponse)(nil), "api.GetDelegateResponse")
	proto.RegisterType((*UpdateDelegateRequest)(nil), "api.UpdateDelegateRequest")
	proto.RegisterType((*UpdateDelegateResponse)(nil), "api.UpdateDelegateResponse")
}

func init() { proto.RegisterFile("proto/proto/api/api.proto", fileDescriptor_15eae2866f8410ca) }

var fileDescriptor_15eae2866f8410ca = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x0d, 0x8a, 0x96, 0x29, 0x28, 0xac, 0xa8, 0x31, 0x82, 0x94, 0x9c, 0x04, 0x31, 0x81,
	0x54, 0x1f, 0xc0, 0x10, 0x90, 0xe2, 0x45, 0x22, 0x5e, 0xbc, 0x6d, 0xd2, 0x61, 0xb3, 0x12, 0xbb,
	0x6b, 0x76, 0x22, 0xfa, 0x30, 0xbe, 0xab, 0x64, 0x93, 0x94, 0xf4, 0xe3, 0xd2, 0xc3, 0x2e, 0xcc,
	0xcc, 0x6f, 0xfe, 0xf3, 0x05, 0x97, 0xba, 0x52, 0xa4, 0xc2, 0xf6, 0xe7, 0x5a, 0x36, 0x2f, 0xb0,
	0x16, 0xdb, 0xe7, 0x5a, 0x7a, 0x93, 0x61, 0x9c, 0x7e, 0x35, 0x9a, 0x70, 0x8e, 0x25, 0x0a, 0x4e,
	0xd8, 0x62, 0xfe, 0x3d, 0xb0, 0x27, 0xa4, 0xa4, 0x73, 0xa6, 0xf8, 0x55, 0xa3, 0x21, 0x76, 0x0d,
	0xd0, 0x73, 0xb3, 0xc4, 0x75, 0x26, 0xce, 0xcd, 0x41, 0x3a, 0xf0, 0xf8, 0x31, 0x9c, 0xae, 0x64,
	0x19, 0xad, 0x16, 0x06, 0xd9, 0x2d, 0x8c, 0x7a, 0xc8, 0x26, 0x8d, 0xa3, 0x93, 0xc0, 0x56, 0x0d,
	0x96, 0xe8, 0x12, 0xf0, 0x13, 0x38, 0x7b, 0xd3, 0x73, 0x4e, 0xb8, 0x5e, 0x7c, 0x27, 0x95, 0x08,
	0xce, 0xd7, 0x55, 0xba, 0x66, 0x5c, 0x38, 0x32, 0x75, 0x9e, 0xa3, 0x31, 0x56, 0x65, 0x94, 0xf6,
	0x66, 0xf4, 0xe7, 0x00, 0x3c, 0xbe, 0xcc, 0x5e, 0xb1, 0xfa, 0x96, 0x39, 0xb2, 0x18, 0xc6, 0x83,
	0x61, 0xd8, 0x45, 0xd0, 0x2c, 0x71, 0x73, 0x29, 0x9e, 0xbb, 0x19, 0x68, 0x4b, 0xf9, 0x7b, 0xec,
	0x19, 0x8e, 0x57, 0xdb, 0x60, 0x9e, 0xa5, 0xb7, 0x4e, 0xe8, 0x5d, 0x6d, 0x8d, 0xf5, 0x62, 0xf1,
	0xc3, 0xfb, 0x54, 0x48, 0x2a, 0xea, 0x2c, 0xc8, 0xd5, 0x67, 0x28, 0x15, 0xe1, 0x8f, 0xae, 0xd4,
	0x07, 0xe6, 0x14, 0x16, 0x52, 0x14, 0x77, 0xc4, 0xb3, 0x12, 0xbb, 0xa3, 0x0a, 0x55, 0xf2, 0x85,
	0x68, 0xee, 0x9e, 0x1d, 0x5a, 0xcf, 0xf4, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x3d, 0x77, 0x08,
	0x15, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServiceClient interface {
	GetDelegate(ctx context.Context, in *GetDelegateRequest, opts ...grpc.CallOption) (*GetDelegateResponse, error)
	UpdateDelegate(ctx context.Context, in *UpdateDelegateRequest, opts ...grpc.CallOption) (*UpdateDelegateResponse, error)
}

type aPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAPIServiceClient(cc *grpc.ClientConn) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) GetDelegate(ctx context.Context, in *GetDelegateRequest, opts ...grpc.CallOption) (*GetDelegateResponse, error) {
	out := new(GetDelegateResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/GetDelegate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) UpdateDelegate(ctx context.Context, in *UpdateDelegateRequest, opts ...grpc.CallOption) (*UpdateDelegateResponse, error) {
	out := new(UpdateDelegateResponse)
	err := c.cc.Invoke(ctx, "/api.APIService/UpdateDelegate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
type APIServiceServer interface {
	GetDelegate(context.Context, *GetDelegateRequest) (*GetDelegateResponse, error)
	UpdateDelegate(context.Context, *UpdateDelegateRequest) (*UpdateDelegateResponse, error)
}

// UnimplementedAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServiceServer struct {
}

func (*UnimplementedAPIServiceServer) GetDelegate(ctx context.Context, req *GetDelegateRequest) (*GetDelegateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelegate not implemented")
}
func (*UnimplementedAPIServiceServer) UpdateDelegate(ctx context.Context, req *UpdateDelegateRequest) (*UpdateDelegateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDelegate not implemented")
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_GetDelegate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetDelegate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/GetDelegate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetDelegate(ctx, req.(*GetDelegateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_UpdateDelegate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDelegateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).UpdateDelegate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIService/UpdateDelegate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).UpdateDelegate(ctx, req.(*UpdateDelegateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDelegate",
			Handler:    _APIService_GetDelegate_Handler,
		},
		{
			MethodName: "UpdateDelegate",
			Handler:    _APIService_UpdateDelegate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto/api/api.proto",
}
